baseURL = 'https://ethsteel.github.io/'
languageCode = 'en-us'
title = 'STEEL'
theme = "minimal"
sectionPagesMenu = ""
[markup]
[markup.goldmark.renderer]
      unsafe = true

[params]
  sectionPagesMenu = ""  # Disable auto menu generation
  favicon = "favicon.ico"