baseURL = 'https://steel.ethereum.foundation/'
languageCode = 'en-us'
title = 'STEEL'
theme = "minimal"
sectionPagesMenu = ""
canonifyURLs = true
[markup]
[markup.goldmark.renderer]
unsafe = true

[params]
#sectionPagesMenu = ""   # Disable auto menu generation
favicon = "favicon.ico"
